#!/usr/bin/env bash
# Write deploy/kbs.env and ConfigMap kbs-ca for inference workloads.
# Modes: local (from cluster route) | remote (KBS_URL + KBS_CA_FILE or KBS_ENDPOINT_DIR).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=../defaults.sh
source "$SCRIPT_DIR/../defaults.sh"

KBS_MODE="${KBS_MODE:-local}"
OUT_ENV="${OUT_ENV:-$ROOT/deploy/kbs.env}"
KBS_ENDPOINT_DIR="${KBS_ENDPOINT_DIR:-$OPERATOR_BUNDLE}"

oc whoami >/dev/null || { echo "oc login required (inference cluster)" >&2; exit 1; }

resolve_remote_inputs() {
  if [[ -n "${KBS_URL:-}" && -n "${KBS_CA_FILE:-}" && -f "$KBS_CA_FILE" ]]; then
    return 0
  fi
  if [[ -f "$KBS_ENDPOINT_DIR/kbs.url" && -f "$KBS_ENDPOINT_DIR/kbs-ca.pem" ]]; then
    KBS_URL="$(tr -d '\n' <"$KBS_ENDPOINT_DIR/kbs.url")"
    KBS_CA_FILE="$KBS_ENDPOINT_DIR/kbs-ca.pem"
    return 0
  fi
  echo "Remote KBS: set KBS_URL + KBS_CA_FILE, or run operator-export-kbs-endpoint into $KBS_ENDPOINT_DIR" >&2
  exit 1
}

case "$KBS_MODE" in
  local)
    KBS_HOST="$(oc get route kbs-service -n "$TRUSTEE_NS" -o jsonpath='{.spec.host}')"
    KBS_URL="https://${KBS_HOST}"
    TMP_CERT="$(mktemp)"
    oc get secret trustee-tls-cert -n "$TRUSTEE_NS" -o jsonpath='{.data.tls\.crt}' | base64 -d >"$TMP_CERT"
    KBS_CA_FILE="$TMP_CERT"
    ;;
  remote)
    resolve_remote_inputs
    TMP_CERT=""
    ;;
  *)
    echo "KBS_MODE must be local or remote (got $KBS_MODE)" >&2
    exit 1
    ;;
esac

mkdir -p "$(dirname "$OUT_ENV")" "$DEMO_NAMESPACE"
cat >"$OUT_ENV" <<EOF
# Generated by scripts/kbs/configure-kbs.sh (KBS_MODE=$KBS_MODE)
KBS_URL=${KBS_URL}
KBS_RESOURCE_PATH=${KBS_RESOURCE_PATH}
EOF

oc create namespace "$DEMO_NAMESPACE" --dry-run=client -o yaml | oc apply -f - >/dev/null 2>&1 || true
oc create configmap kbs-ca \
  --from-file=ca.pem="$KBS_CA_FILE" \
  -n "$DEMO_NAMESPACE" \
  --dry-run=client -o yaml | oc apply -f -

[[ -n "${TMP_CERT:-}" ]] && rm -f "$TMP_CERT"

echo "KBS_MODE=$KBS_MODE"
echo "KBS_URL=$KBS_URL"
echo "Wrote $OUT_ENV"
echo "ConfigMap kbs-ca updated in namespace $DEMO_NAMESPACE"
